### ISSUE TITLE
Uninstalling game doesnt work

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [RZetko/galaxy-integration-ffxiv#4]
Hey,

currently attempting to uninstall the game using the plugins uninstall_game method through Galaxy uninstall game button will fail. 

```
2019-10-14 16:23:17,734 - root - INFO - Handling notification: method=uninstall_game, params={'game_id': 'final_fantasy_xiv_shadowbringers'}
2019-10-14 16:23:17,843 - root - ERROR - Task exception was never retrieved
future: <Task finished coro=<FinalFantasyXIVPlugin.uninstall_game() done, defined at C:\Users\User\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-integration-ffxiv-1.1.1 (1)\plugin.py:148> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-integration-ffxiv-1.1.1 (1)\plugin.py", line 149, in uninstall_game
    self._game_instances[0].delete_game()
  File "C:\Users\User\AppData\Local\GOG.com\Galaxy\plugins\installed\galaxy-integration-ffxiv-1.1.1 (1)\ffxiv_localgame.py", line 22, in delete_game
    subprocess.Popen(ffxiv_tools.get_uninstall_exe(), creationflags=0x00000008, cwd = self._dir, shell=True)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 775, in __init__
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1119, in _execute_child
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 523, in list2cmdline
TypeError: 'NoneType' object is not iterable
2019-10-14 16:23:18,539 - root - DEBUG - Received 55 bytes of data
2019-10-14 16:23:18,540 - root - INFO - Handling request: id=96, method=ping, params={}
```

I see that there is a difference between what the get_uninstall_exe() method looks for in registry and what i have in mine 

![image](https://user-images.githubusercontent.com/48480506/66759358-651ba780-eea0-11e9-9915-88d9d64684cd.png)

Hope this helps

**Comment by RZetko** [comment]
Thanks for detailed bug report and helping me with solving this. I updated registry paths for uninstalling game and this issue should be fixed in v1.1.2. If you notice any problems, please let me know.
